version: "3"
services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"

  api:
    container_name: Back-end
    build:
      context: ./Back-end
      dockerfile: Dockerfile
    image: pp/backend
    ports:
      - "3333:3333"
    volumes:
      - ./Back-end:/usr/src/app
    depends_on:
      - db

  client:
    container_name: Front-end
    build:
      context: ./Front-end
      dockerfile: Dockerfile
    image: pp/Front-end
    ports:
      - "3000:3000"
    volumes:
      - ./Front-end:/usr/src/app
    depends_on:
      - api
